### PR TITLE
Removes Export to CSV button

### PR DESCRIPTION
**Pull request by William-Liang808**
https://www.hawaii.edu/jira/browse/GROUPINGS-1089

[Groupings-1089](https://www.hawaii.edu/jira/browse/GROUPINGS-1089)

# Test Checklist

- [x ] Unit Tests Passed:
- [x ] Jasmine Tests Passed:
- [x ] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
I think we should be careful to make sure that the export to csv is not needed before removing it. In terms of code this is fine.

**Comment by William-Liang808** [comment]
> 

This should be fine as the export to csv button is still present on the application, just not in modal so it does not fully remove the functionalities of exporting to csv format. This ticket seemed to have just been on visuals mismatching on both branches.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good!

**Review by mhodgesatuh — APPROVED** [review]
looks very straight forward

**Pull request merged**
