### PR TITLE
Switch to JUnit 5

### PR DESCRIPTION
**Pull request by michho8**
# Ticket Link

[Ticket GROUPINGS-1340](https://uhawaii.atlassian.net/browse/GROUPINGS-1340)

# List of squashed commits

- Migrate GroupingsRestControllerTest to Junit5
- Change GroupingServiceResultException to Junit5
- Change GroupingsHTTPExceptionTest to Junit5
- Change GroupingsServiceResultTest to Junit5
- Change AnnoymousUserTest to Junit5
- AuthorizationServiceTest to Junit5
- RoleHolderTest to Junit5
- RoleTest to Junit5
- UhCasAttributesTest to Junit5
- UserBuilderTest to Junit5
- UserContextServiceTest to Junit5
- UserDetailsServiceTest to Junit5
- UserTest to Junit5
- WIP errors with Zak
- Resolve UserBuilderTest Junit4 methods not found
- UserContextServiceTest and UserTest to Junit5
- UserBuilderTest assertThat containsString
- UserContextServiceTest and groupings/configuration files to Junit5 except SecurityConfigTest
- Add back @RunWith statements
- UserBuilderTest Matcher assertThat
- UhCasAttributesTest to UserTest assertThat and @ExtendWith
- AppConfigRunTest @ExtendWith
- Up to SecurityConfigTest to Junit5
- Revisions to use Matcher assertThat and depreciated values
- Controller folder
- Exceptions, service, and type folder
- Changes imports and tests of JsonUtilTest and StringsTest
- JsonUtilTest to pass
- Access folder finalized
- Configuration finalized
- Controller finalized
- Exceptions finalized
- Service finalized
- Type finalized and previous files use 'is'
- Util finalized

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]

**Review by mhodgesatuh — COMMENTED** [review]
checks are failing.  They need to be addressed.

**Comment by michho8** [comment]
image

**Comment by michho8** [comment]
image

**Review by zakgilbert — APPROVED** [review]

**Review by JorWo — APPROVED** [review]

**Review by mhodgesatuh — APPROVED** [review]
Love the dramatic change in code coverage :-)

**Pull request merged**
