### PR TITLE
Fix 'Manage My Groupings Fleeting Pagination Presentation Bug'

### PR DESCRIPTION
**Pull request by mikhail-shkaralevich**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1703)

# List of squashed commits

- Fix 'Manage My Groupings Fleeting Pagination Presentation Bug'

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Jasmine Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Comment by mikhail-shkaralevich** [comment]
Please note that I fixed the issue by setting the page to the first one when switching back to the "List all members" window. Is this the behavior we would expect?

**Comment by mikhail-shkaralevich** [comment]
Also, I have a question, what's the point of calling `reloadGrouping()` when we switch to the "List all members" window from another window? It just seems to reload what's already loaded.

**Comment by JorWo** [comment]
> Also, I have a question, what's the point of calling `reloadGrouping()` when we switch to the "List all members" window from another window? It just seems to reload what's already loaded.

We wanted the grouping to always stay updated by making it double as the reload button, but I have noticed some side-effects where I did want to reload the grouping because the grouping was large. I would really like to have an individual reload button instead.

**Review by JorWo — APPROVED** [review]
That's really smart and intuitive, great work.

**Comment by JorWo** [comment]
> Please note that I fixed the issue by setting the page to the first one when switching back to the "List all members" window. Is this the behavior we would expect?

Yeah that seems to make a lot of sense; reloading the grouping should reset you to the first page.

**Comment by mhodgesatuh** [comment]
That's an interesting idea.  If you write up a ticket we can add that
feature n 2.6 or 2.7

**Comment by JorWo** [comment]
One question though, did you find any side-effects with this approach? Maybe you cannot change pages when a large grouping is loading?

**Review by mhodgesatuh — APPROVED** [review]
Impressive that the change is this light.

**Comment by mhodgesatuh** [comment]
Note that the ticket is actually for 2.5

**Comment by mikhail-shkaralevich** [comment]
> Note that the ticket is actually for 2.5

Yes, I noticed it but the bug was still present.

**Comment by mikhail-shkaralevich** [comment]
> One question though, did you find any side-effects with this approach? Maybe you cannot change pages when a large grouping is loading?

I still can change pages while it is loading.

**Comment by mikhail-shkaralevich** [comment]
> That's an interesting idea. If you write up a ticket we can add that feature n 2.6 or 2.7





> > Also, I have a question, what's the point of calling `reloadGrouping()` when we switch to the "List all members" window from another window? It just seems to reload what's already loaded.
> 
> We wanted the grouping to always stay updated by making it double as the reload button. Sometimes there could be two people making changes to the grouping at once, so we will need to reload the grouping. However I have noticed some side-effects where I did not want to reload the grouping because the grouping was large. I would really like to have an individual reload button instead.

Would the button be accessible from all windows of the "manage grouping page"?

**Comment by mhodgesatuh** [comment]
I've not thought about the UI/UX.  So someone needs to prose it. Maybe good
discussion for the next meeting?

**Comment by mikhail-shkaralevich** [comment]
> That's an interesting idea. If you write up a ticket we can add that feature n 2.6 or 2.7

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1709)

**Comment by mhodgesatuh** [comment]
Thanks, I updated the ticket, and also moved it out of the parking lot.  If
you are working on it you still need to move it to the "in progress" swim
lane.

**Comment by JorWo** [comment]
Make sure to backport to devrc-2-5-0.

**Pull request merged**
