### PR TITLE
Standardize display info in confirmation modals #671

### PR DESCRIPTION
**Pull request by devgav**

### CODE REVIEW

**Comment by Kobeyarai808** [comment]
Looks Like Codacy did not like this. I will investigate. 

This pull request is kind of large, I think that this should be the upper limit of how big a pull request should be. Anything larger I feel might cause conflicts as it might be hard to track of how stale branches are. 

In general.controller.js, why was a 3rd equals sign added in boolean expressions in multiple locations? My current knowledge is that the "equals" operation should be "==" or only be two equals signs. Please let me know why my understanding does not line up with yours. 

Other than those small comments, this branch looks good. Now to look at Codacy to find out what's going on!

**Comment by Kobeyarai808** [comment]
I just looked on Codacy, if you do not want to go through Codacy the issue seems to be a very minor syntax error. 

On mainv2_3.css line 441, the indentation seems to slightly off, I took a look at the commit and in GitHub I cannot see the indentation so I am not sure what's going on. Can you please take a look into satisfying Codacy? If not, No worries! Codacy might be broken again. 

Link to Codacy: https://app.codacy.com/gh/uhawaii-system-its-ti-iam/uh-groupings-ui/pullRequest?prid=8443036

**Comment by devgav** [comment]
> Looks Like Codacy did not like this. I will investigate.
> 
> This pull request is kind of large, I think that this should be the upper limit of how big a pull request should be. Anything larger I feel might cause conflicts as it might be hard to track of how stale branches are.
> 
> In general.controller.js, why was a 3rd equals sign added in boolean expressions in multiple locations? My current knowledge is that the "equals" operation should be "==" or only be two equals signs. Please let me know why my understanding does not line up with yours.
> 
> Other than those small comments, this branch looks good. Now to look at Codacy to find out what's going on!

I believe in JS the "==" changes the two thing's you are comparing to the same type so I should go back and change some of the @param label back to a string instead of an object. It makes more sense to me to use the "===" so that we don't get that type conversion which could cause unexpected results. I will also go back and work on shortening down this pull request I believe because of my merge that is why it is showing a bunch of other peoples commits...

**Comment by mhodgesatuh** [comment]
Codacy is reporting the indentation issue because we previously agreed that we indent 4 spaces and I updated Codacy accordingly.  The file us using a 2 character indent.  I recommend we consistently use 4 character indentations.

**Comment by devgav** [comment]
I fixed the codacy issues and changed the @param {object} to @param {string}. To get rid of what happened with other peoples commits in mines I squashed their changes with mines.

**Comment by fduckart** [comment]
Hey, what does this mean?: "squashed their changes with mine". That sounds extraordinary unusual.

**Comment by devgav** [comment]
> Hey, what does this mean?: "squashed their changes with mine". That sounds extraordinarily unusual.

Sorry about that, before it was showing a bunch of other peoples commits with mines in the pull request so to make the pull request look cleaner I squashed those commits into the "standardized display user info in modals".

**Review by Kobeyarai808 — COMMENTED** [review]
This looks good.

**Comment by ruizaj** [comment]
Also looks fine to me, I will commit the PR.

**Pull request merged**
