### PR TITLE
Fix Codacy Code Style Issues

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[Groupings-539](https://uhawaii.atlassian.net/browse/GROUPINGS-539)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
looks like a very nice code cleanup pass

**Comment by fduckart** [comment]
Can you squash all these commits into a single one?

**Comment by fduckart** [comment]
Looks great. One thing I'm a bit curious about is the angular.extend updates. What we had there before is just like the numerous examples on the web. Did we remove the extra "$scope" because Codacy was complaining about it or something?

**Comment by JorWo** [comment]
> Looks great. One thing I'm a bit curious about is the angular.extend updates. What we had there before is just like the numerous examples on the web. Did we remove the extra "$scope" because Codacy was complaining about it or something?

Yes, this is the issue in question: [link](https://app.codacy.com/gh/uhawaii-system-its-ti-iam/uh-groupings-ui/issues?&filters=W3siaWQiOiJMYW5ndWFnZSIsInZhbHVlcyI6W119LHsiaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6W119LHsiaWQiOiJMZXZlbCIsInZhbHVlcyI6W119LHsiaWQiOiJQYXR0ZXJuIiwidmFsdWVzIjpbIjQ0NzY4Il19LHsiaWQiOiJBdXRob3IiLCJ2YWx1ZXMiOltdfV0=)

**Review by devgav — APPROVED** [review]
Thanks for cleaning up the codacy issues.

**Pull request merged**
