### PR TITLE
Add count of retrieved members to other groupings tab

### PR DESCRIPTION
**Pull request by yertsti**
# Ticket Link

[1317](https://uhawaii.atlassian.net/browse/GROUPINGS-1317)

# List of squashed commits

- Remove getting members... message added spinner to header for each groupings tab
- Add count of retrieved members to other groupings tab

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues

**Comment by yertsti** [comment]
Do you know if it is possible to run codacy locally?

**Comment by JorWo** [comment]
> Do you know if it is possible to run codacy locally?

Codacy uses eslint, and we can export the Codacy rules to a eslint file.

**Review by JorWo — APPROVED** [review]
Looks good.

**Pull request merged**
