### PR TITLE
Create testing/refactor network call in GroupingRestController

### PR DESCRIPTION
**Pull request by zakgilbert**
***COMMITS***
- Refactor RestController URI query building.
- Refactor GroupingsService URI query building.
---
[GROUPINGS-1120](https://www.hawaii.edu/jira/browse/GROUPINGS-1120)
- [x] Unit
- [x] Jasmine
- [x] Visual Inspection

### CODE REVIEW

**Comment by zakgilbert** [comment]
Kinda fumbling with the Codacy errors but still working on it.

**Comment by fduckart** [comment]
Not sure if we have them already, but I would have expected to see a bunch of tests checked in with these kind of changes.

**Comment by devgav** [comment]
> Kinda fumbling with the Codacy errors but am working on it.

With ES6 you should be able to just do this:

` let params = {
       page,
       size,
       sortString,
       isAscending
 };`

https://attacomsian.com/blog/javascript-object-property-shorthand

Pretty sure this will solve some of the codacy errors as well

**Comment by devgav** [comment]
Also, for your query you could do something like this instead of using the Object.Keys

`                let query = (params) => { 
                    let value = [];
                    for (const key in params) {
                        value = encode(key) + "=" + encode(params[key])
                    }
                    value.join("&");
                    return value;
                }`

**Review by devgav — APPROVED** [review]

**Review by mhodgesatuh — APPROVED** [review]
URIBuilder is a nice addition, especially since it reduces custom code.

**Pull request merged**
