### PR TITLE
Add codeql.yml removed LGTM badges and added codeql badge

### PR DESCRIPTION
**Pull request by yertsti**
Testing to see if it runs on dev branch

Codeql now runs on master

# Ticket Link

[1267](https://uhawaii.atlassian.net/browse/GROUPINGS-1267)

# List of squashed commits

- Testing to see if it runs on dev branch
- Codeql now runs on master

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Not sure what to make of the "Code scanning / CodeQL" notices that now appear.

**Comment by yertsti** [comment]
I'm not sure either because it didn't find any problems when I tested it on the dev branch.

**Comment by mhodgesatuh** [comment]
This reminds me of similar reports that we saw in the past and determined to be false positives, but since two of them are critical we need to follow up on them before merging this I think.  We have to at least ensure that the two critical are false positives if that is the case.  I brief glance at one of them did not reveal to me any filtering/sanitization to ensure the security of the input.

**Comment by yertsti** [comment]
I looked at LGTM for this repository and the two critical alerts are the same as on LGTM [https://lgtm.com/projects/g/uhawaii-system-its-ti-iam/uh-groupings-ui/?mode=list&id=java%2Fssrf](https://lgtm.com/projects/g/uhawaii-system-its-ti-iam/uh-groupings-ui/?mode=list&id=java%2Fssrf). I'm guessing this has been a problem, but we just didn't notice because the alert was out of the way.

**Comment by devgav** [comment]
It looks like you can dismiss the issues that are false positives. Although I would be careful and make sure to do some research first, probably best to bring it up in a team meeting to discuss whether these are false positives or not since some of the other team members might have worked on addressing these in the past.

image

**Comment by mhodgesatuh** [comment]
I concur.  Let's discuss at our team meeting.  Thanks!

**Comment by fduckart** [comment]
Do me a favor and remove all the comments from that codeql.yml file. Also, can you find out if we can add a file to our workflow that CodeQL will use to exclude some things we determine are either false positives or stuff we want to ignore?

**Comment by fduckart** [comment]
I think we tried this before, but can you try this experiment anyway?... change the GroupingsRestController#adminLists method to this:


```    
    @GetMapping(value = "/adminLists")
    public ResponseEntity<String> adminLists(Principal principal) {
        logger.info("Entered REST adminLists...");
        String principalName = policy.sanitize(principal.getName());
        String uri = API_2_1_BASE + "/admins-and-groupings";
        return httpRequestService.makeApiRequest(principalName, uri, HttpMethod.GET);
    }
```

I wanna see what happens with the scanning.

**Comment by devgav** [comment]
After discussing with the other branch leads I think we decided it is ok to go forward and merge this ticket. However, I have created another ticket https://uhawaii.atlassian.net/browse/GROUPINGS-1270 to address the warnings and failures that CodeQL is reporting and how to possibly ignore and test some of these issues.

**Review by devgav — APPROVED** [review]

**Pull request merged**
