### PR TITLE
Remove appConfigRun and move file path to .properties file

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1051](https://www.hawaii.edu/jira/browse/GROUPINGS-1051)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
I am investigating removing the AppConfigRun.java

**Comment by fduckart** [comment]
Did you mean to make this a pull request? It's not ready for that, of course.

**Comment by devgav** [comment]
> Did you mean to make this a pull request? It's not ready for that, of course.

oops i thought i had drafted this since i am trying to figure out why the coverage/build and the java version tests are failing

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.  Looks like a nice cleanup.

**Comment by fduckart** [comment]
Don't merge this until we are ready, eh.

**Review by fduckart — CHANGES_REQUESTED** [review]
Testing the 'Request changes' review option.

**Comment by fduckart** [comment]
Still trying to find some features related the github workflow for this one. The PR is not properly assembled (or close to ready), so not sure how to mark this in github. Any ideas related to the github workflow here?

**Comment by mhodgesatuh** [comment]
Re: Any ideas related to the github workflow here?
Maybe the PR should be closed and the development work allowed to progress further until it is again time to test the PR waters.

**Comment by devgav** [comment]
Closing this pr as it is still not ready.

**Pull request closed without merging**
