### PR TITLE
Updates reset checkboxes functionality

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1524)

# List of Squashed Commits 
- Makes helper function
- Makes jasmine tests

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Comment by JorWo** [comment]
Let's do some refactoring:
1. Move both if statements outside and after the while loop.
2. I am hoping that we do not need Object.entries(), not entirely sure
3. If possible, have one variable for includeCheck/Disable and one variable for excludeCheck/Disable. Then we can get rid of the if statements and just say `$scope.includeCheck =$scope.groupingInclude === 0` or $`scope.excludeCheck = $scope.groupingExclude === 0`
4. Add a Jasmine test case
Thanks!

**Review by JorWo — APPROVED** [review]
Nice work!

**Comment by JorWo** [comment]
Could you add a test case for $scope.getGroupingInformation() to test that $scope.disableResetCheckboxes() has been called? Thanks.

**Review by mhodgesatuh — APPROVED** [review]
Nice work

**Pull request merged**
