### PR TITLE
Created Regex Global Pattern

### PR DESCRIPTION
**Pull request by Kobeyarai808**
# Ticket Link

[Groupings-1082](https://www.hawaii.edu/jira/browse/GROUPINGS-1082)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by devgav — APPROVED** [review]

**Review by mhodgesatuh — APPROVED** [review]
Note that the pattern works for both the uid and the uhUuid, by design, so it's name is not perfect, but that is already.  However, the inline documentation  above 638 should clarify this.

**Review by mhodgesatuh — APPROVED** [review]
Looks good

**Comment by mhodgesatuh** [comment]
Are we still getting the eslint checks, etc?  It is not clear that we are and they are important.

**Comment by Kobeyarai808** [comment]
It looks like Codacy is working on my end. Are you saying that Codacy does not check eslint in it anymore?
Screen Shot 2022-04-29 at 2 13 40 PM

**Comment by mhodgesatuh** [comment]
Thanks for highlighting the codacy call.  I didn't see it.  Glad it is there.

**Pull request merged**
