### PR TITLE
Changes to Login/logout button alignment and scss navbar

### PR DESCRIPTION
**Pull request by Louie808**
# Ticket Link

[1355](https://uhawaii.atlassian.net/browse/GROUPINGS-1355)

# List of squashed commits

- Changes to Login/logout button alignment
- updates scss navbar

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]

**Review by mhodgesatuh — COMMENTED** [review]
Codacy reports a missing } issue.  Likely your IDE also flagged it.

**Comment by JorWo** [comment]
What is your opinion on having the logout button have the same font as the rest of the navbar (1.2 rem)? If it looks better at the current font (1 rem), could you rename the scss class from btn-vertAlign to btn-v-align to make class naming consistent? Thanks.

**Review by JorWo — COMMENTED** [review]
Could you make the "a" in .btn-v-Align lowercase and don't forget to update the class in menubar.html.

**Comment by Louie808** [comment]
Michael said in the meeting that the font size inside the button can be left alone and is not compelling enough. Changning the font also messes with the size of button and the css made to move the button down.

**Pull request merged**
