### PR TITLE
Locating and Removing unused Images from project

### PR DESCRIPTION
**Pull request by buccatm**
UH Grouping 1045

Remove all unused images from the project.
This was tested by doing grep to locate unused images, then run the project normally with the images removed.
Finally tested the project with mvn clean then mvn clean test, the result was no test failed.

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
What was the purpose of introducing this change? (spreading this across 3 lines)
`                                <echo>
                                    https://www.hawaii.edu/bwiki/display/SITARd/Unit+Testing#UnitTesting-RunningYourTest
                                </echo>`

**Comment by buccatm** [comment]
I was testing the Ctrl+Alt+L when I finally got my inteljj set up properly. When I ran the command, it reformated my project to the proper style. And I forgot to undo this change before I committed the work I did for this issue.

**Comment by mhodgesatuh** [comment]
On the positive side, now we know that the file is formatted according to our standard practices.

**Review by mhodgesatuh — APPROVED** [review]
I see no issues that have not already been discussed.

**Comment by mhodgesatuh** [comment]
Added Kobey as a reviewer too.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good, for future reference, please use the template that Eric has given us when making pull requests. Great work!

**Pull request merged**
