### PR TITLE
Fix using trashcan to remove old test accounts from Admins

### PR DESCRIPTION
**Pull request by imths**
# Ticket Link

[Groupings-1568](https://uhawaii.atlassian.net/browse/GROUPINGS-1568?atlOrigin=eyJpIjoiNjVmZTQ1NDk5MWU5NGI2YTg2NmExNzVjMWExNmZiNzIiLCJwIjoiaiJ9)

# List of squashed commits

- None

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Jasmine Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Looks like another nice catch.  I'll need to also see this in action before approving though.

**Comment by JorWo** [comment]
This change is a bit weird, it makes it so that the last else statement can never be reached.

**Review by mhodgesatuh — COMMENTED** [review]
the member.username reference is a red flag for me since we've agreed to replace the use of username for variables and attributes to uid.  Does the member object need to be updated?  That's how it appears to me at first glance.

**Comment by JorWo** [comment]
I believe our API response for retrieving the list of Admins still uses
username as the uid. Misha is currently working on ticket to update that.

**Comment by mhodgesatuh** [comment]
Sounds good.  We can push this PR through and wait for the next to make the
correction.
Thanks

**Review by JorWo — APPROVED** [review]
Looks good!

**Pull request merged**
