### PR TITLE
Jasmine Testing for adding members to include through file upload

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1048](https://www.hawaii.edu/jira/browse/GROUPINGS-1048)

# List of squashed commits
 Finish testing for addMultipleMembers, addMembers, readAsTextFile
Add addMultipleMembers testing
Change test names to non uhuuid or uuid
Create testing for import button
create testing for addMembers
Create testing for readTextFile

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Comment by devgav** [comment]
I removed the handleSuccessfulAdd function that I had in the Jasmine testing. I was talking with @fduckart and I think we should be treating the functions without $scope to be private functions. Similar to how in JUnit we can't test private methods directly.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good to me too! Great work.

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good!

**Pull request merged**
