### PR TITLE
Fix placeholder message on include/exclude html

### PR DESCRIPTION
**Pull request by Rubegen**
# https://uhawaii.atlassian.net/browse/GROUPINGS-1246

[1246](https://uhawaii.atlassian.net/browse/GROUPINGS-1246)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]

**Comment by devgav** [comment]
These changes seem simple enough. ALthough as a reminder for future pr's i would go through the test checklist to make sure that other parts of the application are nto affected by these changes.

**Comment by mhodgesatuh** [comment]
Probably best to require that here too so that we are consistent.

**Comment by devgav** [comment]
> Probably best to require that here too so that we are consistent.

Good point. Can you go through those test checklist before proceeding with the merge @Rubegen.

**Comment by devgav** [comment]
Seems like there are merge conflicts with some recent merges for this pr. Let me know if you need help sorting any of this out

**Comment by devgav** [comment]
> I thought that PR 684 did the changes for some of these files. Not 100% about that, though.

Yeah, I think  you are right this did change something in PR 684 which explains the merge conflicts,

**Comment by JorWo** [comment]
Closing this PR because another PR (https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/684) was merged already with the exact same changes.

**Pull request closed without merging**
