### PR TITLE
Error message for adding invaild users to Owner

### PR DESCRIPTION
**Pull request by chakhon**
[GROUPINGS-920](https://www.hawaii.edu/jira/browse/GROUPINGS-920)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Please include Andre and Kobey as reviewers since they are both branch managers.

**Comment by fduckart** [comment]
I think it would be awesome if you could take a crack at renaming the "existsInGrouper" function. It started life a year ago as a boolean-like function, but now as become a different beast altogether. A new name that didn't imply it was a boolean function would be the smallest, most helpful change, methinks,

**Comment by chakhon** [comment]
> A new name that didn't imply it was a boolean function would be the smallest, most helpful change,

Created ticket [GROUPINGS-931](https://www.hawaii.edu/jira/browse/GROUPINGS-931) to address the issue.

**Comment by ruizaj** [comment]
Looks good, you can go ahead with the merge.

**Pull request merged**
