### PR TITLE
Remove kotlin plugin from pom.xml

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-1140](https://www.hawaii.edu/jira/browse/GROUPINGS-1140)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
I couldn't find the kotlin plugin on the master API side of the project

**Review by mhodgesatuh — APPROVED** [review]
No idea why it was put here in the first place.  Not by design.

**Review by mhodgesatuh — APPROVED** [review]
Looks good

**Review by fduckart — COMMENTED** [review]
Great.

**Pull request merged**
