### PR TITLE
Fixes the manage memberships table

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[GROUPINGS-1278](https://uhawaii.atlassian.net/browse/GROUPINGS-1278)
done in conjunction with: https://github.com/uhawaii-system-its-ti-iam/uh-groupings-api/pull/388

# List of squashed commits

- Removes filter for membershipResults
- Adds managePersonResults from API
- Edits tests for getMembershipResults and makes test for managePersonResults
- Adds sanitizer to membershipResults 
- Changes safeInput to principalName

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Code changes look good, but there is a vulnerability warning, probably related to the ones we've pondered previously.  Please experiment with using a sanitizer.  Even if it doesn't work we might want to leave the sanitizing code in place.

**Review by devgav — APPROVED** [review]
Thanks for adding the sanitizer to our fnc.

**Comment by fduckart** [comment]
Looks awesome. Can you rename the 'safeInput' variable to 'principalName' or something like that? Also, is it possible to use the safe string for the first argument in makeApiRequest, too?

**Comment by devgav** [comment]
Thanks for making that variable name change. This looks like it is related to https://github.com/uhawaii-system-its-ti-iam/uh-groupings-api/pull/388 on the API side of our project. I messaged Kailee about that pr to review Frank's comment since it seems like you are calling the new REST API endpoint that Kailee created.

**Pull request merged**
