### PR TITLE
spring boot v2.7.14 released, upgrade projects

### PR DESCRIPTION
**Pull request by FeimeiChen**
# Ticket Link

[Ticket 1522](https://uhawaii.atlassian.net/browse/GROUPINGS-1522)

# List of squashed commits

- Commit 1: Spring boot v2.7.14 released, upgrade projects

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Not clear to me why we would skip the jasmine tests in this scenario.

**Comment by JorWo** [comment]
I will help you look more into the Jasmine issue.

**Comment by JorWo** [comment]
Turns out `./mvnw clean jasmine:test` is broken but luckily `./mvnw clean jasmine:bdd` still works.

**Comment by FeimeiChen** [comment]
> Turns out `./mvnw clean jasmine:test` is broken but luckily, `./mvnw clean jasmine:bdd` still works.

done, it works and all passed, thank you so much

**Review by JorWo — APPROVED** [review]

**Pull request merged**
