### PR TITLE
Updates PasswordScanner and adds its tests

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-836](https://www.hawaii.edu/jira/browse/GROUPINGS-836)

# List of squashed commits

- Delete checkForPwd in SpringBootWebApplication
- Adds test resources folder
- Updates PasswordScanner and adds PatternPropertyChecker
- Adds PasswordScannerTest and PatternPropertyCheckerTest
- Removes unused imports and fixes codacy errors

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Codacy is unhappy with the following (and I agree :-)

List<String> patternLocation = new ArrayList<>();;

**Comment by mhodgesatuh** [comment]
Can you also check for unused imports.  Codacy mentions them too.  If you aren't able to access the Codacy checks, try scrolling to the bottom of the Some checks not successful box.

**Comment by KaileeHung** [comment]
Removed checkforpwd but codacy is giving an unused error, this didn't happen on the api side when we did the same thing, so I'm not sure what's off here.

**Comment by mhodgesatuh** [comment]
Codacy believes that this private method is not used.  Can you check and confirm?

private void checkForPwd() throws IOException {

**Comment by KaileeHung** [comment]
Yes, checkForPwd() is not used anywhere

**Comment by mhodgesatuh** [comment]
In that case, it should be removed since we avoid committing unused code.  Thanks for checking.

**Comment by KaileeHung** [comment]
The method was removed earlier though, so I'm not sure why it's showing up on Codacy.

**Comment by devgav** [comment]
> The method was removed earlier though, so I'm not sure why it's showing up on Codacy.

This could be a false positive that codacy is giving since i see in your diff that you deleted the checkForPwd(). You could maybe try and check if there are lingering usages of this fnc, if not then u can maybe do some small change like remove an empty space at the end of a file and then push it up to see if codacy gives the same error.

**Comment by fduckart** [comment]
It appears to be an integration bug with Codacy. The issue is shown as "fixed" on the Codacy site. I'm not sure why github is hiccuping on this update.

**Comment by fduckart** [comment]
The issue appears to a confusion with the Codacy analysis site. Since the un-used code is still in the dev-2-2-0 branch, Codacy still considers it an issue. Codacy should limit their analysis to the branch in the PR, in my view, but it appears it doesn't.

**Comment by mhodgesatuh** [comment]
I have adjusted codacy to ignore the dev-2-2-0 branch.  And added the badges branch, just to see how that works out.

**Review by devgav — APPROVED** [review]
Branch leads have discussed that it is fine to go merge this PR with the current codacy issue

**Pull request merged**
