### PR TITLE
Changes scss configuration to compressed style

### PR DESCRIPTION
**Pull request by KaileeHung**
# Ticket Link

[GROUPINGS-1204](https://uhawaii.atlassian.net/browse/GROUPINGS-1204)

# List of squashed commits

- Changes scss configuration to compressed style
- Fixes merge conflicts

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Not sure how to proceed since the file changes can't be reviewed.  Might have do some manual cut/paste into the contents to explain the code changes, assuming that the changes are not voluminous.

**Comment by mhodgesatuh** [comment]
Codacy is reporting issues with indenting only 2 columns; we can ignore these since the CSS generation doesn't allow us to set an indent level, but there are other reported CSS issues that should be reviewed first.  

Kailee, is there a ticket to try to minify the generated CSS in order to mitigate Codacy's indentation reporting?  Not sure if you created a ticket for that, or someone else did.

**Comment by KaileeHung** [comment]
> Codacy is reporting issues with indenting only 2 columns; we can ignore these since the CSS generation doesn't allow us to set an indent level, but there are other reported CSS issues that should be reviewed first.
> 
> Kailee, is there a ticket to try to minify the generated CSS in order to mitigate Codacy's indentation reporting? Not sure if you created a ticket for that, or someone else did.

I think that would be this ticket? Right now I'm trying to look at the different ways the the file can be formatted in a way that Codacy hopefully won't complain.

**Comment by mhodgesatuh** [comment]
Thanks for researching this.  I'll see if we can get Codacy to accept 2 character indents just for CSS files, in case we conclude that this is the optimal option.  I suspect that a minified CSS is beneficial regardless since a) it would further discourage people from editing it, b) it would download faster.

**Review by devgav — COMMENTED** [review]
This might help for ignoring files w/ codacy so we don't check that css fle https://docs.codacy.com/repositories-configure/codacy-configuration-file/

**Review by devgav — APPROVED** [review]
Other than the codacy error this pr looks fine. We will eventaully need to ignore that css file

**Review by mhodgesatuh — APPROVED** [review]
thumbs up :-)

**Comment by mhodgesatuh** [comment]
With luck I have instructed Codacy to ignore the remaining 14 reported css issues such that we get clean reports.  We'll see.

**Pull request merged**
