### PR TITLE
Moved th:src to after th:srcset

### PR DESCRIPTION
**Pull request by Kobeyarai808**
# Groupings-1028

[Groupings-1028](https://www.hawaii.edu/jira/browse/GROUPINGS-1028)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Not sure who, but someone is working to remove the /seal directory so that all images are in the one directory.  Can you ping the team to see if that is the case and if so who you need to coordinate with?

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Comment by fduckart** [comment]
I kinda wish the alt tag wasn't in between the srcset and src tags.

**Comment by mhodgesatuh** [comment]
Contacting Kobey for this one is a good idea.
thanks

**Comment by devgav** [comment]
Just got a response back from Kobey. He has been very busy with his internship, but he said the best option to implement these changes would be to either pull in or copy these changes from this branch and repush a more updated version so we do not get any merge conflicts.

**Comment by devgav** [comment]
Closing this as I have created another branch that has the most recent version of master with these same changes. The new pr can be found here -> https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/610

**Pull request closed without merging**
