### PR TITLE
Add host name to feedback email

### PR DESCRIPTION
**Pull request by yertsti**
# Ticket Link

[882](https://uhawaii.atlassian.net/browse/GROUPINGS-882)

# List of squashed commits

- Add host name to feedback email

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues.

**Review by JorWo — COMMENTED** [review]
Is it possible to avoid using a try-catch block?

**Comment by yertsti** [comment]
Would it be better to have the method throw the exception instead of a try-catch block?

**Comment by JorWo** [comment]
> Would it be better to have the method throw the exception instead of a try-catch block?



> Would it be better to have the method throw the exception instead of a try-catch block?

Sorry, I just saw that EmailService runs the same way with a try-catch. We can keep the try-catch for now.

**Review by JorWo — APPROVED** [review]

**Pull request merged**
