### PR TITLE
2.2.0 ADA bugs /info page

### PR DESCRIPTION
**Pull request by chakhon**
[GROUPINGS-937](https://www.hawaii.edu/jira/browse/GROUPINGS-937)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
For my edification, what does changing role from "presentation" to "img" contribute to resolution of the ADA shortcoming?

**Comment by mhodgesatuh** [comment]
And there's a plan to port this to master?

**Comment by chakhon** [comment]
> For my edification, what does changing role from "presentation" to "img" contribute to resolution of the ADA shortcoming?

The [presentation role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role) remove an elements implicit native semantics, I am not sure how that applies to an  element. The axe Dev tools tells us that "ARIA role presentation is not allowed for given element", so I replaced it with the "img" role instead. Perhaps I could use "aria-hidden" instead.

**Comment by chakhon** [comment]
> And there's a plan to port this to master?

I will have to discuss this with Kobey and Zak.

**Review by zakgilbert — APPROVED** [review]

**Pull request merged**
