### PR TITLE
Icon for last grouping owner

### PR DESCRIPTION
**Pull request by goodroach**
# Ticket Link

[Groupings 1292](https://uhawaii.atlassian.net/browse/GROUPINGS-1292)

# List of squashed commits

- Icon for last grouping owner

# Test Checklist

- [Y] Unit Tests Passed:
- [Y] Jasmine Tests Passed:
- [Y] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
See slack message on suggested text for the tooltip.

**Review by mhodgesatuh — COMMENTED** [review]
ng-if="groupingOwners.length === 1">

I suspect that this should be == given that this is about count rather than an object equivalency.  Any use of an inequality would further suggest that I'm correct.

**Comment by JorWo** [comment]
> ng-if="groupingOwners.length === 1">
> 
> I suspect that this should be == given that this is about count rather than an object equivalency. Any use of an inequality would further suggest that I'm correct.

It's a good practice to use === instead of == in Javascript since it is not a strongly-typed language. Using == will convert the type, meaning 1 == "1" is true while 1 === "1" is false.  Also, Codacy likes throwing an error for using == instead of ===.

**Review by JorWo — COMMENTED** [review]
Can you show a picture? This can be done during the meeting too.

**Pull request merged**
