### PR TITLE
Groupings-892

### PR DESCRIPTION
**Pull request by mikel-ishihara**
This is for adding padding above the reset grouping column in a grouping's preferences. This code is the same as the code that was pushed to dev-2-2-0 already for the same purpose.

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
likely this will also need to be ported to dev-2-2-0.

**Review by Kobeyarai808 — COMMENTED** [review]
This looks good, no regressions.

**Comment by fduckart** [comment]
You should use Bootstrap 4, eh.

**Comment by mhodgesatuh** [comment]
Please create another ticket referencing this one and requesting that the next iteration of the code utilize bootstrap 4.  Thanks.

**Comment by mhodgesatuh** [comment]
I plan on creating a new ticket to have a team member perform a comprehensive review of our code to see where we aren't, but should be using bootstrap.

**Comment by fduckart** [comment]
You just need to put something like this in the class attribute: pt-4

See here: https://getbootstrap.com/docs/4.5/utilities/spacing/

**Pull request merged**
