### PR TITLE
Fixed ManagePerson page bug

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1306)

# List of squashed commits

- Edited names of variables
- Edited tests
- Editing endpoints
- Fixed ManagePerson page bug 

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
The "username" change/reference reminds me of a conversation we had to standardize on "uid", "uhUuid", and "uhIdentifier" for values provided by the user that could be either one.

**Comment by fduckart** [comment]
That 'member' variable in the managePersonResults javascript function is a bit funny-looking. Is that used?

**Comment by carolwong492** [comment]
> That 'member' variable in the managePersonResults javascript test function is a bit funny-looking. Is that used?

managePersonResults requires something being sent in, so member is just an undefined variable for managePerson to look up and to test against the URL

**Comment by JorWo** [comment]
> The "username" change/reference reminds me of a conversation we had to standardize on "uid", "uhUuid", and "uhIdentifier" for values provided by the user that could be either one.

All functions in the Rest controller all use uid for both uid and uhUuid parameters. Maybe there should be a ticket to replace "uid" with "uhIdentifier" in the UI and API Rest controllers.

**Comment by mhodgesatuh** [comment]
Please go ahead and create the ticket for epic 2.3 to ensure that uid is
not used where uhUuid is also in scope for the variable.

**Review by JorWo — CHANGES_REQUESTED** [review]

**Review by JorWo — APPROVED** [review]
Looks good.

**Pull request merged**
