### PR TITLE
Makes the tooltip directive

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[GROUPINGS-1325](https://uhawaii.atlassian.net/browse/GROUPINGS-1325)

# List of Squashed Commits
- Makes the jasmine test for the tooltip directive
- Replaces all tooltips with the directive

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues

**Review by JorWo — COMMENTED** [review]
Could you replace all of our tooltips with this directive and make a Jasmine test?

**Comment by JorWo** [comment]
Also, the "placement" attribute may be too vague. Since "tooltip-placement" is already taken, we can go with "tooltip-position".

**Comment by Kristyn-Mimura** [comment]
> Also, the "placement" attribute may be too vague. Since "tooltip-placement" is already taken, we can go with "tooltip-position".

I tried making the attribute "tooltip-placement" but after trial and error, it seems you can't uppercase or special characters and it has to be one word. Is "tooltipdirection" ok?

**Comment by JorWo** [comment]
> > Also, the "placement" attribute may be too vague. Since "tooltip-placement" is already taken, we can go with "tooltip-position".
> 
> I tried making the attribute "tooltip-placement" but after trial and error, it seems you can't uppercase or special characters and it has to be one word. Is "tooltipdirection" ok?

Maybe you can do attrs["tooltip-direction"]. Otherwise, tooltipdirection is fine.

**Comment by Kristyn-Mimura** [comment]
> > > Also, the "placement" attribute may be too vague. Since "tooltip-placement" is already taken, we can go with "tooltip-position".
> > 
> > 
> > I tried making the attribute "tooltip-placement" but after trial and error, it seems you can't uppercase or special characters and it has to be one word. Is "tooltipdirection" ok?
> 
> Maybe you can do attrs["tooltip-direction"]. Otherwise, tooltipdirection is fine.

I tried using hyphens but it didn't work, I'l use tooltipdirection

**Comment by JorWo** [comment]
I found that Angular.js converts camel casing to the dash casing: https://stackoverflow.com/questions/25807763/custom-angularjs-directive-including-a-dash-in-the-name-doesnt-work

**Comment by Kristyn-Mimura** [comment]
I accidentally merged a previous commit with the commit for this ticket so I'm closing this ticket and making a new pull request.

**Pull request closed without merging**
