### PR TITLE
add ng-clock to hide numberOfMembership & numberOfGroupings javascript

### PR DESCRIPTION
**Pull request by chakhon**
[GROUPINGS-915](https://www.hawaii.edu/jira/browse/GROUPINGS-915)
Used ng-clock from angularjs to hide javascript code.

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
This looks like a better approach.  Thanks!
We need to ensure this is also ported to 2-2-0

**Comment by Kobeyarai808** [comment]
This looks great! Thanks for fixing this, it's been a recurring issue!

**Comment by Kobeyarai808** [comment]
Also I would like to thank you for adding the link to the ticket. It made it really easy to review. 

I forgot to mention that this is all good to merge!

**Comment by mhodgesatuh** [comment]
And for 2.2.0.  Is that taken care of, or is there a ticket.  Apologies if I missed this being mentioned before; I'm having a very busy vacation :-)

**Comment by Kobeyarai808** [comment]
Yes, I believe this has been ported to 2-2-0. Hope you are enjoying your vacation Michael! I am also having a busy vacation, super fun!

**Pull request merged**
