### PR TITLE
clean up application-localhost.properties file

### PR DESCRIPTION
**Pull request by FeimeiChen**
# Ticket Link

[Ticket 1478](https://uhawaii.atlassian.net/browse/GROUPINGS-1478)

# List of squashed commits

- Commit 1:clean up application-localhost.properties file

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Not sure about this.  The UI uses CAS to authenticate.  Did these settings move to elsewhere?

**Comment by FeimeiChen** [comment]
> Not sure about this. The UI uses CAS to authenticate. Did these settings move to elsewhere?
So only the API side will stop using CAS?

**Comment by fduckart** [comment]
Looks good. I think the Jira asked for the CAS properties to be removed, which is okay because these values are already in the default properties file.

**Review by mhodgesatuh — APPROVED** [review]

**Review by JorWo — APPROVED** [review]
Looks good.

**Pull request merged**
