### PR TITLE
Remove multiple members from UH Groupings doesn't work #933

### PR DESCRIPTION
**Pull request by devgav**

### CODE REVIEW

**Comment by devgav** [comment]
Squashed commits and fixed the member names being displayed.

**Comment by devgav** [comment]
These changes also need to go to 2-2 I am making a separate branch for that

**Comment by Kobeyarai808** [comment]
This looks good to me!

**Comment by devgav** [comment]
I created a dev-2-2-0 version of this branch [here](https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/442)

**Comment by nadine-alcantara** [comment]
Looks good, thank you for moving the admin modal functionality in the admin controller.

**Comment by ruizaj** [comment]
Everything looks in check to me. I will also be pushing this pull request.

**Pull request merged**
