### PR TITLE
Dev buccatm 1105

### PR DESCRIPTION
**Pull request by buccatm**
# Ticket Link

[GROUPINGS-1105](https://www.hawaii.edu/jira/browse/GROUPINGS-1105)

# List of squashed commits

- Bumped version 2.4.4.RELEASE to 2.6.6 to address spring version 5.2 critical Vulnrability
- Bumped spring version to 5.3.18 using 2.5.12 rather than 2.6.6 to mach API side

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by devgav** [comment]
Can you please go through the test checklist so that we know that each of them have successfully passed.

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues, but do note that you need to go through the checklist before Gavin can approve

**Comment by buccatm** [comment]
Sorry about that, I completely forgot to check the checklist, before I made this pull request. 

So I was able to run mvn clean test & mvn clean test -Dtest=StringsTest. Both results was no failure on my end.
I was also able to run the mvn jasmine:bdd test, and when I ran it the test result was no failure.

As for the general visual inspection. I was able to run the app and was able to run normally with no functionality problem on the site.

However, at the moment my forked API side is broken since I accidentally push some commits on my master branch and as a result, I am unable to rebase and update my api master branch to the current upstream master. I am unable to fix the problem at this time, due to my internship.

Also currently [dev-buccatm-1105](https://github.com/buccatm/uh-groupings-ui/tree/dev-buccatm-1105) , seems to be borken. For some reason this branch is 152 commits ahead and 198 commits behind uhawaii-system-its-ti-iam:master.

**Comment by devgav** [comment]
> Sorry about that, I completely forgot to check the checklist, before I made this pull request.
> 
> So I was able to run mvn clean test & mvn clean test -Dtest=StringsTest. Both results was no failure on my end. I was also able to run the mvn jasmine:bdd test, and when I ran it the test result was no failure.
> 
> As for the general visual inspection. I was able to run the app and was able to run normally with no functionality problem on the site.
> 
> However, at the moment my forked API side is broken since I accidentally push some commits on my master branch and as a result, I am unable to rebase and update my api master branch to the current upstream master. I am unable to fix the problem at this time, due to my internship.
> 
> Also currently [dev-buccatm-1105](https://github.com/buccatm/uh-groupings-ui/tree/dev-buccatm-1105) , seems to be borken. For some reason this branch is 152 commits ahead and 198 commits behind uhawaii-system-its-ti-iam:master.

I am going to hold off on committing this for now as this could mean that there may be some hidden regressions in this PR with our master branch. I think that your branch may be out of sync with the master because you have not done a rebase with master in a while. If these changes are still necessary I can draft them. If not I think we should close this PR for now and you can work on getting this branch back in sync with our master branch.

**Comment by devgav** [comment]
Closing this pr. Marcos will reopen this ticket whenever he gets back from his internship.

**Pull request closed without merging**
