### PR TITLE
Add babel dependency to pom file

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Link

[GROUPINGS-323](https://www.hawaii.edu/jira/browse/GROUPINGS-323)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Why do we need the babel dependency?

**Comment by devgav** [comment]
> Why do we need the babel dependency?

Babel mainly helps with browser compatibility by changing new js syntax to js syntax that is supported across older browsers.

**Review by mhodgesatuh — APPROVED** [review]
I see no issues

**Comment by devgav** [comment]
Here is a list of browser versions that don't currently support the ES6 syntax -> https://caniuse.com/?search=es6

The browser versions that don't support ES6 is mainly from 2009 - 2013. And the ones that have partial support range from 2014-2017.

**Comment by mhodgesatuh** [comment]
The official supported ITS browsers: <https://www.hawaii.edu/askus/717>
As long as we support these we are good.
 - Michael

**Comment by fduckart** [comment]
Don't you have to do something with that babel dependency for it to be able to work it's magic?

**Pull request closed without merging**
