### PR TITLE
Remove unnecessary instances of "localTest" activeProfile from UI side

### PR DESCRIPTION
**Pull request by Rubegen**
# Ticket Link

[1101](https://www.hawaii.edu/jira/browse/GROUPINGS-1101)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by fduckart — COMMENTED** [review]
Love it!

**Review by fduckart — COMMENTED** [review]
Oh, just noticed something... please take out the relevant import statements. Also, make sure the code formatting is done.... seems some extra blank lines are showing up.

**Review by mhodgesatuh — COMMENTED** [review]
I'm deferring to Frank on this one.

**Review by devgav — APPROVED** [review]
Thank you for removing the rest of the unnecessary imports. As a tip you can have intelliJ automatically remove unused imports by going to 

File > Settings > Editor > General > Auto Import > Check "Optimize imports on the fly".
then click Apply and Ok.

Alternatively you can use the command CTRL + ALT + O (windows) | option + control + o

I have updated our IntelliJ Tips and Tricks to include this so future team members will know as well. 
https://www.hawaii.edu/bwiki/pages/viewpage.action?pageId=776405261

**Pull request merged**
