### PR TITLE
Deletes interface files

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1350)

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues

**Review by JorWo — APPROVED** [review]
Looks great

**Review by JorWo — CHANGES_REQUESTED** [review]
I think UhCasAttributes would be a better name than UhAttributes because it is more specific.

**Comment by mhodgesatuh** [comment]
That occurred to me too, but I wasn't clear if the attributes were strictly from CAS or if CAS was a subset.  The other thing that occurred to me that is some day we might switch to Shibboleth and drop CAS, and it would be nice not to have to change the variable name.

**Comment by JorWo** [comment]
> That occurred to me too, but I wasn't clear if the attributes were strictly from CAS or if CAS was a subset. The other thing that occurred to me that is some day we might switch to Shibboleth and drop CAS, and it would be nice not to have to change the variable name.

That seems better to not have to change the name. I'll proceed with merging.

**Review by JorWo — APPROVED** [review]

**Pull request merged**
