### PR TITLE
Adds padding and adjust table headings

### PR DESCRIPTION
**Pull request by carolwong492**
# Ticket Link

[Ticket](https://uhawaii.atlassian.net/browse/GROUPINGS-1195)

# List of squashed commits
- Fixes code indentation to 4 spaces

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
A previous PR also triggered a Codacy complaint that the indentation should be 4 spaces rather than 2 and for that PR we agreed to placate Codacy.  Not sure why the main branch didn't already have the new spacing though.

**Comment by JorWo** [comment]
You can press cmd+option+L in mainv2_3.css to reformat to 4 spaces.

**Comment by carolwong492** [comment]
> You can press cmd+option+L in mainv2_3.css to reformat to 4 spaces.

When I do that, it says the code is already formatted correctly, and git status says nothing's changed.

**Comment by JorWo** [comment]
> > You can press cmd+option+L in mainv2_3.css to reformat to 4 spaces.
> 
> When I do that, it says the code is already formatted correctly, and git status says nothing's changed.

I'm currently using the default code style in Intellij and it seems to reformat properly.

**Comment by carolwong492** [comment]
> I'm currently using the default code style in Intellij and it seems to reformat properly.

I think I'm using the Project code style. My code is already indented with 4 spaces though, so I'm not sure why the Codacy test is failing.

**Comment by zakgilbert** [comment]
I don't think our project code style XML includes CSS formatting specifications, so it probably runs the default IntelliJ settings.

**Comment by zakgilbert** [comment]
Perhaps check the CSS code style in your settings. Here is what mine looks like.
image

**Comment by carolwong492** [comment]
> Perhaps check the CSS code style in your settings. Here is what mine looks like. 

Mine looks the same. 
Screen Shot 2022-08-31 at 10 24 03 PM

**Comment by carolwong492** [comment]
Okay, I found the issue! I was editing the wrong files. Thank you everyone for your help!

**Review by zakgilbert — APPROVED** [review]

**Review by devgav — APPROVED** [review]
Nice to see the codacy isssues finally fixed. Maybe you can coordinate with @KaileeHung to help fix her issues with the knowledge that you learned from this ticket

**Pull request merged**
