### PR TITLE
Fix owners not being able to opt out of groupings

### PR DESCRIPTION
**Pull request by devgav**
[GROUPINGS-1044](https://www.hawaii.edu/jira/browse/GROUPINGS-1044)
- [x] Jasmine Test 
- [x] Unit Test 
- [x] Basic Visual Inspection

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Looks good.

**Comment by mhodgesatuh** [comment]
Is this a problem on the master branch too?

**Review by Kobeyarai808 — APPROVED** [review]
Looks good!

**Comment by devgav** [comment]
> Is this a problem on the master branch too?

not right now, I believe this is an issue because Zak found a piece of code that was filtering out the members that weren't in exclude and not in basis in the getMembershipResults() function and he removed it in his latest pr for 2.2, but those changes aren't in master as of now

**Review by zakgilbert — APPROVED** [review]

**Pull request merged**
