### PR TITLE
add ng-clock to hide numberOfMembership & numberOfGroupings javascript for 2-2-0

### PR DESCRIPTION
**Pull request by chakhon**
[GROUPINGS-915](https://www.hawaii.edu/jira/browse/GROUPINGS-915)
Used ng-clock from angularjs to hide javascript code.

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
And bingo!!!  It is also being ported.  Wonderful!

**Comment by Kobeyarai808** [comment]
I'm not branch manager for 2-2-0 but I like these changes. Great work! This has been a really big issue for the QA. I will go and update the QA sheet after Zak approves and I fully test it.

**Comment by Kobeyarai808** [comment]
Also, I really appreciate you adding the link to the ticket here. 

I forgot to mention, please feel free to merge when you are ready.

**Review by zakgilbert — APPROVED** [review]

**Comment by fduckart** [comment]
No big deal at all, but the issue title misspells "cloak".

**Pull request merged**
