### PR TITLE
Fix white space above Reset Grouping - Groupings - 892

### PR DESCRIPTION
**Pull request by William-Liang808**
- [x] Basic visual inspection
[Groupings - 892](https://www.hawaii.edu/jira/browse/GROUPINGS-892)

### CODE REVIEW

**Comment by William-Liang808** [comment]
In the same scss file, there are comments denoted with the double-slash "//" and was not flagged by codacy. Is this an issue that I should fix for all the scss files to use "/* */" for commenting or should I stick with the format that is already there?

**Comment by fduckart** [comment]
Maybe related?:  https://github.com/stylelint/stylelint/issues/4877

**Review by Kobeyarai808 — CHANGES_REQUESTED** [review]
Could you please take care of the codacy issue? https://app.codacy.com/gh/uhawaii-system-its-ti-iam/uh-groupings-ui/pullRequest?prid=8861408 

Other than that issue everything looks good, will approve once this is taken care of.

**Comment by Kobeyarai808** [comment]
> In the same scss file, there are comments denoted with the double-slash "//" and was not flagged by codacy. Is this an issue that I should fix for all the scss files to use "/* */" for commenting or should I stick with the format that is already there?

I am not sure, maybe ask Michael? I imagine that fixing just this file should suffice.

**Pull request closed without merging**
