### PR TITLE
Remove multiple members from UH Groupings doesn't work, dev-2-2-0 #933

### PR DESCRIPTION
**Pull request by devgav**
These are the changes made for master [here](https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/440), but on the dev-2-2-0 branch.

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Were the codacy issues investigated?  I know that some, like the leading underscore, we live with, but the others should be reviewed: <https://app.codacy.com/gh/uhawaii-system-its-ti-iam/uh-groupings-ui/pullRequest?prid=8532553>

**Comment by mhodgesatuh** [comment]
Maybe focus on the one marked as "medium" level of concern.

**Comment by zakgilbert** [comment]
One of the issues with codacy can be fixed easy, "the functions used before declared error." Those are local functions so just move them to the top of the Controller so that they are in the namespace before being called/passed.

**Comment by devgav** [comment]
I believe this is a false positive for Codacy (Found fs.open with non literal argument at index 0) we don't use the fs.open in the admin.controller.js

**Comment by Kobeyarai808** [comment]
Is there any way to quickly fix the codacy false positive? I do see what you mean about how fs.open is not used. There are also 2 other issues in codacy, did you see anything for this?

**Comment by devgav** [comment]
> Is there any way to quickly fix the codacy false positive? I do see what you mean about how fs.open is not used. There are also 2 other issues in codacy, did you see anything for this?

I believe one of the codacy issues is ('_' is not defined.) which @mhodgesatuh said that we just live with this error. The other error is this (Function has a complexity of 5. Maximum allowed is 4.) I asked @zakgilbert about that since he has dealt with this issue before, I believe you have to rewrite the function so it never has a complexity > 4 although it is just a single _forEach loop so I am not sure how to rewrite this.

**Comment by Kobeyarai808** [comment]
In that case, I feel it should be fine to merge for now. Can you please document this? I will ask Zak for assistance to understand Codacy better and hopefully get this resolved.

**Comment by devgav** [comment]
> 

sure I can document this on bwiki, do we have a codacy issues on there?

**Comment by Kobeyarai808** [comment]
Sorry I was not clear. I was thinking about jotting all of these finicky Codacy bugs on a ticket for someone to investigate and fix in the future.

**Comment by devgav** [comment]
> Sorry I was not clear. I was thinking about jotting all of these finicky Codacy bugs on a ticket for someone to investigate and fix in the future.

Ticket created [GROUPINGS-958](https://www.hawaii.edu/jira/browse/GROUPINGS-958?jql=project%20%3D%20GROUPINGS%20AND%20reporter%20is%20not%20EMPTY%20AND%20reporter%20%3D%20gavin4)

**Comment by Kobeyarai808** [comment]
Once again, when you are ready, you can merge.

**Comment by zakgilbert** [comment]
My bad I though I approved this.

**Pull request merged**
