### PR TITLE
Create an action tab for groupings

### PR DESCRIPTION
**Pull request by michho8**
# Ticket Link

[Ticket 1344](https://uhawaii.atlassian.net/browse/GROUPINGS-1344)

# List of squashed commits

- Move reset functions from preferences to actions tab
- Change header name and simplify actions.html

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by michho8** [comment]
Before 
image

After
image
image

**Review by mhodgesatuh — APPROVED** [review]

**Comment by JorWo** [comment]
Could you try out these changes to the side-nav?:
1. Swap the position of Settings with Actions (Settings is usually the last tab in a list)
2. Use circle-caret-right (or square-caret-right if circle does not exist) as the icon for Actions (Just like the GitHub actions tab above)

I had this other idea of having Sync Destinations as its own tab because of how important Sync Destinations are to the UH Groupings app. Then Settings can group together the actions and user options. Anyway that should be for a future discussion when there exists more actions, user options, and sync destinations.

**Comment by mhodgesatuh** [comment]
added Jordan since he is the Branch Lead

**Review by zakgilbert — APPROVED** [review]
I like @JorWo 's idea of putting the preferences at the bottom.

**Comment by mhodgesatuh** [comment]
The order I recommend is: Sync Destinations, Preferences, Actions.

**Review by JorWo — APPROVED** [review]

**Pull request merged**
