### PR TITLE
Sanitize Uploaded Files

### PR DESCRIPTION
**Pull request by devgav**
# Ticket Name

Sanitize Uploaded Files

# List of squashed commits

- Implement sanitize function on UI side
- Fix trailing comma issue
-  Remove the .pop

# Test Checklist

- [x] Integration Passed:
- [x] Unit Passed:
- [x] General Inspection

# Link to Ticket

[[Ticket](Insert Link Here)](https://www.hawaii.edu/jira/secure/RapidBoard.jspa?rapidView=100&view=detail&selectedIssue=GROUPINGS-1047)

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Note that I've shared the regex expressions with Julio in case he's aware of edge cases that need to be anticipated.  Will update here when I get feedback.

**Comment by mhodgesatuh** [comment]
Julio's code review feedback regarding the regex patterns in the general controller:

There are often exceptions, so I'm worried about putting this in the code. The UH Number for misc usernames is currently the same as the username. There are usernames with leading underscores for application accounts, and those also are treated as the UH Number. There might be exceptions to the username being 8 characters, but I'll have to verify if they are usernames or just an alias in Google. There may be some old usernames with underscores in them.

The code has the regexs swapped too. UhUuid is typically the numeric one of size 8.

Better to sanitize for security (avoid large strings, code injection, etc.) and make some assumptions that are likely to work in the future rather than hardcode the format of the uhUuid/uid in the application code.

Julio's recommendation:

Maybe something simple like alphanumeric and underscores are allowed with a maximum of 30 chars for either uh number or uh username
no spaces, no punctuation, etc. of course

**Review by mhodgesatuh — CHANGES_REQUESTED** [review]
See the comments Julio provided.  The regex patterns, besides being switched, are going to trip on the uhUuid and uid edge cases.  Do not promote this to 220 as is.

**Comment by devgav** [comment]
if it turns out that our definition of a uhuuid and a uid can't be easily covered using regex then I can use an alternative solution, with [DOMPurify](https://www.npmjs.com/package/dompurify), which filters out what dompurify considers harmful code. It will still leave the <></> tags in but remove the harmful part of the tag.

**Comment by mhodgesatuh** [comment]
Actually, the regex solution is very straight forward.  We just need to agree on what characters are allowed, the the max length.  After consultation with the IAM team, the allowed characters are: [A-Z][a-z][0-9]-_ and a length from 8-64 characters.

**Comment by devgav** [comment]
LMK if there are any more valid/invalid inputs that you would like me to add to the in the sanitize test function.

**Review by Kobeyarai808 — APPROVED** [review]
Looks good to me.

**Review by mhodgesatuh — APPROVED** [review]

**Comment by mhodgesatuh** [comment]
The regex patterns have been corrected, so my concerns have been addressed.

**Pull request merged**
