### PR TITLE
Remove the whitespace above the footer on the home page before login

### PR DESCRIPTION
**Pull request by gitCarrot**
# Ticket Link

[ Ticket 1564 ](https://uhawaii.atlassian.net/browse/GROUPINGS-1564)

# List of squashed commits

- Get rid of footer property
- Remove bootstrap css on the home page after logging in to add margin on the bottom

# Test Checklist

- [x] Exhibits Clear Code Structure:
- [x] Project Unit Tests Passed:
- [x] Project Jasmine Tests Passed:
- [x] Executes Expected Functionality:
- [x] Tested For Incorrect/Unexpected Inputs:

### CODE REVIEW

**Comment by JorWo** [comment]
Were you able to get the Jasmine tests working?

**Comment by gitCarrot** [comment]
> Were you able to get the Jasmine tests working?

**Comment by gitCarrot** [comment]
I tried jasmine tests, and do you think it is supposed to be?

**Comment by JorWo** [comment]
Yep, that’s correct.

**Review by mhodgesatuh — APPROVED** [review]

**Comment by JorWo** [comment]
image

I think it looks a little odd with the unequal spacing with the top and bottom of the white background div. I say let's add some padding so it looks equal:

image

**Comment by mhodgesatuh** [comment]
I second the motion

**Review by JorWo — COMMENTED** [review]
The spacing looks great! One last thing, whenever you edit a .scss file, you will need to update our main css file using the command: `./mvnw sass:update-stylesheets`. So run this command and push the changes up. Thanks!

**Review by JorWo — APPROVED** [review]

**Pull request merged**
