### PR TITLE
Adds Q and A to the What Happens If section

### PR DESCRIPTION
**Pull request by Kristyn-Mimura**
# Ticket Link

[GROUPINGS-1285](https://uhawaii.atlassian.net/browse/GROUPINGS-1285)

# List of squashed commits
- Corrects spelling of reacquire
- Moves text to messages.properties file

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — COMMENTED** [review]
Spelling error persists: "require" is the correction spelling. Currently spelled "recquire" and I'll bet the IDE also flagged the misspelling.  If you aren't familiar with the "Problems" tab in the IDE, LMK for a quick demo.

**Comment by fduckart** [comment]
Just a thought... maybe we should move these text items to the message.properties file?

**Comment by mhodgesatuh** [comment]
actually, that would be consistent with how we manage text in general.  Kristyn, can you take a look, and perhaps update the ticket description?

**Comment by Kristyn-Mimura** [comment]
I got rid of the etc. like Gavin said in the meeting, does this look good?

**Comment by mhodgesatuh** [comment]
For some reason I'm not seeing the "etc" change in the PR.  I'm probably
looking in the wrong place.

**Comment by Kristyn-Mimura** [comment]
> 

Sorry! That was for this ticket: [Changes the home page groupings paragraph #683](https://uhawaii.atlassian.net/browse/GROUPINGS-1287), I put that comment on the wrong PR

**Comment by mhodgesatuh** [comment]
Thanks.  I just figured that out; still catching up on email

**Comment by JorWo** [comment]
Move the text into the messages.properties files and this PR should be good to go.

**Review by JorWo — APPROVED** [review]
Thanks for moving the text into messages.properties.

**Pull request merged**
