### PR TITLE
Change tooltip message

### PR DESCRIPTION
**Pull request by goodroach**
# Ticket Link

[Groupings 1379](https://uhawaii.atlassian.net/browse/GROUPINGS-1379)

# List of squashed commits

- Change the tooltip message

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Can you check the rest of the message properties to see if we normally reference our institution as "UH" or as "the university"?  Best to be consistent.

**Comment by JorWo** [comment]
It seems that we always reference our institution as "UH" and never "the university".

**Comment by mhodgesatuh** [comment]
Thanks.  We'll need to make that fix prior to the commit

**Comment by JorWo** [comment]
Don't forget to fix your commit containing changes to side-nav.html.

**Comment by mhodgesatuh** [comment]
What's the status of this one?  Done or is more work needed.  Jordan?

**Comment by JorWo** [comment]
> What's the status of this one? Done or is more work needed. Jordan?

This one will be closed and I will merge the new PR Hugh created here: https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/786

**Pull request closed without merging**
