### PR TITLE
Fixes missed Codacy code style issues and refactors functions in general.controller.js

### PR DESCRIPTION
**Pull request by JorWo**
# Ticket Link

[Groupings-1191](https://uhawaii.atlassian.net/browse/GROUPINGS-1191)

# List of squashed commits

- Fixed missed code style issues
- In general.controller.js, refactored succesfulAddHandler, getSyncDestValueInArray, getEntireSyncDestValueInArray, and setSyncDestInArray
- Security issues "FOUND FS.OPEN WITH NON LITERAL ARGUMENT AT INDEX 0"  and "Generic Object Injection" are false-positives

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by mhodgesatuh** [comment]
Would be good to do a code walkthrough on this one, unless you've already gotten advice on it perhaps.

**Comment by fduckart** [comment]
Those Javascript updates... some of those things just can't be right. Did Codacy recommend some of those changes? It looks like we are adding a bunch of extra wrapping and type conversions just too fool Codacy.

**Comment by devgav** [comment]
Not sure how i feel about all those parseInt's. I wonder if we can maybe just turn it off in codacy? Seem's like we are parsing an int to an int which is confusing and unnecessary

**Comment by JorWo** [comment]
> Those Javascript updates... some of those things just can't be right. Did Codacy recommend some of those changes? It looks like we are adding a bunch of extra wrapping and type conversions just too fool Codacy.

Codacy did not recommend these changes, it was what I found to get around the issue. I will look more into a better way to fix this security issue, but I'm most likely going to close this PR and ignore the Codacy issue.

**Comment by mhodgesatuh** [comment]
Before ignoring the codacy issue, let's discuss at the team meeting.

**Pull request closed without merging**
