### PR TITLE
Tooltip bugs in /manage-grouping

### PR DESCRIPTION
**Pull request by michho8**
# Ticket Link

[Ticket 1488](https://uhawaii.atlassian.net/browse/GROUPINGS-1488)

# List of squashed commits

- Change to displayPreferenceInfoModal in sync-destinations
- Add dynamic title to modal
- Switch to use displayDynamicModal function
- Fix tooltip for Actions tab
- Delete related custom preference modal code

# Test Checklist

- [X] Unit Tests Passed:
- [X] Jasmine Tests Passed:
- [X] General Visual Inspection:

### CODE REVIEW

**Comment by michho8** [comment]
The `displayPreferenceInfoModal` and all related functions/files can be deleted since it's no longer used. I switched to `displayDynamicModal` instead since I thought it was more applicable for this case. Please let me know if I should switch back for any reason, if not, I'll delete the related files.

**Review by mhodgesatuh — APPROVED** [review]
The code looks good, but I don't see where the custom Preference modal code got removed.  Was glad to here that you could use the generic dynamic model.

**Comment by michho8** [comment]
Just removed the related code, thank you. The generic dynamic modal is very useful!

**Review by mhodgesatuh — APPROVED** [review]
I don't see any issues

**Pull request closed without merging**
