### PR TITLE
Review code and replace custom CSS codes with Bootstrap

### PR DESCRIPTION
**Pull request by sanehirakenji**
# Ticket Link

[Groupings-942](https://uhawaii.atlassian.net/browse/GROUPINGS-942?atlOrigin=eyJpIjoiMmE4MTg2MmI2NzE3NGM5Yzk3MTM2M2UzZTllZmMxZmEiLCJwIjoiaiJ9)

# List of squashed commits

- Converts admin-error-messages.html to bootstrap
- Converts exclude.html and include.html to bootstrap
- Converts groupings-list.html to bootstrap
- Converts manage-grouping.html to bootstrap
- Converts members.html to bootstrap
- Converts preferences.html to bootstrap
- Converts side-nav.html to bootstrap
- Converts admin.html to bootstrap
- Converts feedback.html to bootstrap
- Converts groupings.html to bootstrap
- Converts home.html, info.html, memberships.html, and menubar.html to bootstrap
- Converts CSS Loader to Bootstrap spinner
- Various Merge Conflict fixes

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
This is a very nice cleanup and a healthy reduction in custom code.  Thanks!

**Comment by fduckart** [comment]
Awesome. Can you do me a favor, though, and add in some blank lines for those couple of files missing a new line at the end?

**Review by devgav — COMMENTED** [review]
Looks great. Just going off of Frank but add in the blank lines at groupings.html and admin-error-messages.html. 

Also make sure to compile the scss.
`mvn sass:update-stylesheets`

**Comment by fduckart** [comment]
Also, can you squash the PR into a single commit for me?

**Comment by devgav** [comment]
> Added the blank lines to the end of files that did not have them. Also added a newline as requested by a minor codacity comment. Frank is the "squash and merge" the option for your last request? Or is there a way to combine the commits in the PR before merging?

The command to squash a pr is `git rebase -i HEAD~3`

**Comment by fduckart** [comment]
I would do an interactive rebase to squash the commits. No merging necessary. I typically use the command at the terminal that Gavin mentioned, myself, but use whatever tool your comfortable with.

**Comment by devgav** [comment]
Maybe a more clearer commit will help others who are looking back at the history know what this commit was trying to accomplish

**Review by devgav — APPROVED** [review]
Looks good thanks for squashing those commits.

**Pull request merged**
