### PR TITLE
Change preferences to synchronization destinations

### PR DESCRIPTION
**Pull request by yertsti**
# Ticket Link

[1321](https://uhawaii.atlassian.net/browse/GROUPINGS-1321)

# List of squashed commits

- Change preferences to synchronization destinations
- Add html attribute to fix tooltip on preferences
- Remove tooltip directive

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by JorWo — COMMENTED** [review]
I noticed you created a custom directive for the sync destination tooltips. I know that those tooltips have been broken but instead of creating a custom directive, could you try adding this to the HTML?: onmouseover="$(this).tooltip('toggle')". Also, if you could find a better way than adding that HTML attribute, that would be even better.

**Comment by yertsti** [comment]
Ok I'll look into it

**Comment by yertsti** [comment]
I did some googling and if you use uib-tooltip="tooltip" it displays the bootstrap styled tooltip in the ng-repeat block, but the small arrow between the tooltip and the icon doesn't show. I think we would need to update angular or bootstrap or something to get the arrow to show or add some custom css. Also, all the other tooltips in ng-repeat blocks use the onmouseover attribute. Not sure if it is worth trying to figure out how to get uib-tooltip to work.

**Comment by mhodgesatuh** [comment]
Sounds like the uib-tooltip discussion would be a good one for the team meeting.

**Comment by JorWo** [comment]
> I did some googling and if you use uib-tooltip="tooltip" it displays the bootstrap styled tooltip in the ng-repeat block, but the small arrow between the tooltip and the icon doesn't show. I think we would need to update angular or bootstrap or something to get the arrow to show or add some custom css. Also, all the other tooltips in ng-repeat blocks use the onmouseover attribute. Not sure if it is worth trying to figure out how to get uib-tooltip to work.

I tried to get the uib-tooltip to work before but it involves downgrading our Boostrap version, which will break the rest of our UI. The AngularUI Bootstrap library is no longer supported, so I do not expect that bug to be fixed. 

On the bright side, Kristyn is working on a custom directive of a tooltip that mimics the uib-tooltip in this PR: https://github.com/uhawaii-system-its-ti-iam/uh-groupings-ui/pull/713. You can leave the tooltip with the 'onmouseover' attribute and she will later update the tooltip with our new custom directive

**Review by JorWo — APPROVED** [review]

**Pull request merged**
