### PR TITLE
Revised Workflow files 

### PR DESCRIPTION
**Pull request by Erick-Orozco-Ciprian**
# Ticket Link

[Ticket](https://www.hawaii.edu/jira/browse/GROUPINGS-1093)

# List of squashed commits

- Changed to test Java 17 not 18
- Generalized Coverage.yml config

# Test Checklist

- [x] Unit Tests Passed::
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Looks good.  Under what circumstances does the email address get utilized?  Reason I ask is that likely spammers will harvest the email address, so we need to weigh the pros and cons of exposing it.

**Comment by fduckart** [comment]
I think we can make up a random no-reply address since this address is just for the git logging. Maybe something like "actions@noreply.its.hawaii.edu" or some such string.

**Comment by mhodgesatuh** [comment]
Thanks Frank.  Let's run with this suggestion.

**Review by Kobeyarai808 — APPROVED** [review]
I like these new changes.

**Review by devgav — APPROVED** [review]

**Pull request merged**
