### PR TITLE
Dev kobeya 1002 2

### PR DESCRIPTION
**Pull request by Kobeyarai808**
# Ticket Link

[Groupings-1002](https://www.hawaii.edu/jira/browse/GROUPINGS-1002)

# Test Checklist

- [x] Unit Tests Passed:
- [x] Jasmine Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Comment by Kobeyarai808** [comment]
Investigating the Codacy Reports.

**Review by mhodgesatuh — COMMENTED** [review]
I don't understand the .directive, so can't comment on that.  Has Frank reviewed this code?

The text reference "newline characters" is not something you can expect a typical member of the UH community to understand, and that's your audience.  Basically, you need to convey that each entry needs to be on separate line.  For example: "The file should consist if a list of UH Usernames or UH Numbers, one per line."  It is important to note that we have heavily marketed the "UH Username and UH Number" terminology in the UH community and this project needs to consistently use this technology in customer communications, just as it must consistently use "uid" and "uhUuid" in the codes.  Two audiences, two sets of terminology.

**Comment by Kobeyarai808** [comment]
> I don't understand the .directive, so can't comment on that. Has Frank reviewed this code?
> 
> The text reference "newline characters" is not something you can expect a typical member of the UH community to understand, and that's your audience. Basically, you need to convey that each entry needs to be on separate line. For example: "The file should consist if a list of UH Usernames or UH Numbers, one per line." It is important to note that we have heavily marketed the "UH Username and UH Number" terminology in the UH community and this project needs to consistently use this technology in customer communications, just as it must consistently use "uid" and "uhUuid" in the codes. Two audiences, two sets of terminology.

Okay, I will go and fix these. Frank gave me the directive but I don't think he reviewed this pull request yet. I will message him on Slack.

**Review by zakgilbert — APPROVED** [review]

**Review by devgav — APPROVED** [review]

**Review by mhodgesatuh — APPROVED** [review]
Okay to release, but:
I see a few things that might go into a followup ticket:  1) making the regex pattern global or a config property would position the code better for future changes to UH identifiers. 2) the function to massage user input should be a utility or help function that can get used, later, in other places. 3) the importModal text on line 10 be in messages.properties.

**Comment by mhodgesatuh** [comment]
Did a ticket get created to address my points above?

**Comment by Kobeyarai808** [comment]
https://www.hawaii.edu/jira/browse/GROUPINGS-1082, https://www.hawaii.edu/jira/browse/GROUPINGS-1083, and https://www.hawaii.edu/jira/browse/GROUPINGS-1084 were created to address the points brought up in this pull request.

**Pull request merged**
