### PR TITLE
Update Coverage Badge Reference

### PR DESCRIPTION
**Pull request by Erick-Orozco-Ciprian**
Coverage Badge now references the correct script and file

# Ticket Link

[Ticket](https://www.hawaii.edu/jira/browse/GROUPINGS-1068)

# List of squashed commits

- Changed coverage status badge reference 

# Test Checklist

- [x] Unit Tests Passed:
- [x] General Visual Inspection:

### CODE REVIEW

**Review by mhodgesatuh — APPROVED** [review]
Looking forward to seeing this badge for the project.  What's the plan for the API side of the project?

**Comment by Erick-Orozco-Ciprian** [comment]
> Looking forward to seeing this badge for the project. What's the plan for the API side of the project?

Had to update the directory slightly since It goes through the actions directory and not the file directly. The coverage seems to be updating fine so I will make a PR for the API side aswell!

**Review by Kobeyarai808 — APPROVED** [review]
Great job!

**Comment by mhodgesatuh** [comment]
Can the os matrix include centos?  Reason I ask is because it is closer to RHEL, the OS that we use in production.

**Comment by Erick-Orozco-Ciprian** [comment]
> Can the os matrix include centos? Reason I ask is because it is closer to RHEL, the OS that we use in production.

Does not seem to be one of the OSs that GitHub actions have hosted. It does seem possible to set up your own but that requires a bit more work so it may be better to create a separate ticket for the implementation of centos.

**Comment by mhodgesatuh** [comment]
How about fedora?

Probably not necessary to spend too much more time on this.

Michael Hodges
Middleware, Identity and Access Management
University of Hawaii, Information Technology Services
***@***.***
808-956-7195 (GMT -10:00)

we>$

**Comment by Erick-Orozco-Ciprian** [comment]
> How about fedora? Probably not necessary to spend too much more time on this. 

I think github only supports macos, ubuntu, and windows. As mentioned I believe you can create your own "runner" and self-host but it would require a couple of more steps. I'll check in with Frank once these tickets are resolved to see if he has an idea about it!

**Review by devgav — APPROVED** [review]

**Pull request merged**
